ALTER TABLE clinicas ALTER COLUMN specialties SET NOT NULL;
ALTER TABLE medicos ALTER COLUMN address SET NOT NULL;
ALTER TABLE medicos ALTER COLUMN age SET NOT NULL;
ALTER TABLE pacientes ALTER COLUMN address SET NOT NULL;
ALTER TABLE pacientes ALTER COLUMN age SET NOT NULL;